name: metaleader
description: 메타 리더십 수첩

publish_to: 'ITNJ'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  android_id: ^0.3.6
  flutter_inappwebview: ^6.0.0
  flutter_downloader: ^1.11.6
  external_path: ^1.0.3
  uni_links: ^0.5.1
  url_launcher: ^6.2.3


  flutter_localizations:
    sdk: flutter


  firebase_messaging:
  firebase_core:
  firebase_analytics:
  flutter_local_notifications:
  flutter_linkify: ^5.0.2


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

